/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensors.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sensors.pb-c.h"
void   sensors__gps__init
                     (Sensors__Gps         *message)
{
  static const Sensors__Gps init_value = SENSORS__GPS__INIT;
  *message = init_value;
}
size_t sensors__gps__get_packed_size
                     (const Sensors__Gps *message)
{
  assert(message->base.descriptor == &sensors__gps__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__gps__pack
                     (const Sensors__Gps *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__gps__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__gps__pack_to_buffer
                     (const Sensors__Gps *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__gps__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Gps *
       sensors__gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Gps *)
     protobuf_c_message_unpack (&sensors__gps__descriptor,
                                allocator, len, data);
}
void   sensors__gps__free_unpacked
                     (Sensors__Gps *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__gps__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__imu__init
                     (Sensors__Imu         *message)
{
  static const Sensors__Imu init_value = SENSORS__IMU__INIT;
  *message = init_value;
}
size_t sensors__imu__get_packed_size
                     (const Sensors__Imu *message)
{
  assert(message->base.descriptor == &sensors__imu__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__imu__pack
                     (const Sensors__Imu *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__imu__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__imu__pack_to_buffer
                     (const Sensors__Imu *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__imu__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Imu *
       sensors__imu__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Imu *)
     protobuf_c_message_unpack (&sensors__imu__descriptor,
                                allocator, len, data);
}
void   sensors__imu__free_unpacked
                     (Sensors__Imu *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__imu__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__cam__init
                     (Sensors__Cam         *message)
{
  static const Sensors__Cam init_value = SENSORS__CAM__INIT;
  *message = init_value;
}
size_t sensors__cam__get_packed_size
                     (const Sensors__Cam *message)
{
  assert(message->base.descriptor == &sensors__cam__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__cam__pack
                     (const Sensors__Cam *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__cam__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__cam__pack_to_buffer
                     (const Sensors__Cam *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__cam__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Cam *
       sensors__cam__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Cam *)
     protobuf_c_message_unpack (&sensors__cam__descriptor,
                                allocator, len, data);
}
void   sensors__cam__free_unpacked
                     (Sensors__Cam *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__cam__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__lidar__xyz__init
                     (Sensors__Lidar__Xyz         *message)
{
  static const Sensors__Lidar__Xyz init_value = SENSORS__LIDAR__XYZ__INIT;
  *message = init_value;
}
void   sensors__lidar__init
                     (Sensors__Lidar         *message)
{
  static const Sensors__Lidar init_value = SENSORS__LIDAR__INIT;
  *message = init_value;
}
size_t sensors__lidar__get_packed_size
                     (const Sensors__Lidar *message)
{
  assert(message->base.descriptor == &sensors__lidar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__lidar__pack
                     (const Sensors__Lidar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__lidar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__lidar__pack_to_buffer
                     (const Sensors__Lidar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__lidar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Lidar *
       sensors__lidar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Lidar *)
     protobuf_c_message_unpack (&sensors__lidar__descriptor,
                                allocator, len, data);
}
void   sensors__lidar__free_unpacked
                     (Sensors__Lidar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__lidar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__can__init
                     (Sensors__Can         *message)
{
  static const Sensors__Can init_value = SENSORS__CAN__INIT;
  *message = init_value;
}
size_t sensors__can__get_packed_size
                     (const Sensors__Can *message)
{
  assert(message->base.descriptor == &sensors__can__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__can__pack
                     (const Sensors__Can *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__can__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__can__pack_to_buffer
                     (const Sensors__Can *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__can__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Can *
       sensors__can__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Can *)
     protobuf_c_message_unpack (&sensors__can__descriptor,
                                allocator, len, data);
}
void   sensors__can__free_unpacked
                     (Sensors__Can *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__can__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__log__init
                     (Sensors__Log         *message)
{
  static const Sensors__Log init_value = SENSORS__LOG__INIT;
  *message = init_value;
}
size_t sensors__log__get_packed_size
                     (const Sensors__Log *message)
{
  assert(message->base.descriptor == &sensors__log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__log__pack
                     (const Sensors__Log *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__log__pack_to_buffer
                     (const Sensors__Log *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Log *
       sensors__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Log *)
     protobuf_c_message_unpack (&sensors__log__descriptor,
                                allocator, len, data);
}
void   sensors__log__free_unpacked
                     (Sensors__Log *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__algorithm_img__init
                     (Sensors__AlgorithmImg         *message)
{
  static const Sensors__AlgorithmImg init_value = SENSORS__ALGORITHM_IMG__INIT;
  *message = init_value;
}
size_t sensors__algorithm_img__get_packed_size
                     (const Sensors__AlgorithmImg *message)
{
  assert(message->base.descriptor == &sensors__algorithm_img__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__algorithm_img__pack
                     (const Sensors__AlgorithmImg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__algorithm_img__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__algorithm_img__pack_to_buffer
                     (const Sensors__AlgorithmImg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__algorithm_img__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__AlgorithmImg *
       sensors__algorithm_img__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__AlgorithmImg *)
     protobuf_c_message_unpack (&sensors__algorithm_img__descriptor,
                                allocator, len, data);
}
void   sensors__algorithm_img__free_unpacked
                     (Sensors__AlgorithmImg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__algorithm_img__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sensors__gps__field_descriptors[4] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Gps, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Gps, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "horizontalDilutionOfPrecision",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Gps, horizontaldilutionofprecision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Gps, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__gps__field_indices_by_name[] = {
  2,   /* field[2] = horizontalDilutionOfPrecision */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange sensors__gps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sensors__gps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Gps",
  "Gps",
  "Sensors__Gps",
  "sensors",
  sizeof(Sensors__Gps),
  4,
  sensors__gps__field_descriptors,
  sensors__gps__field_indices_by_name,
  1,  sensors__gps__number_ranges,
  (ProtobufCMessageInit) sensors__gps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__imu__field_descriptors[4] =
{
  {
    "scaledAccelX",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Imu, scaledaccelx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scaledAccelY",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Imu, scaledaccely),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scaledAccelZ",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Imu, scaledaccelz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Imu, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__imu__field_indices_by_name[] = {
  0,   /* field[0] = scaledAccelX */
  1,   /* field[1] = scaledAccelY */
  2,   /* field[2] = scaledAccelZ */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange sensors__imu__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sensors__imu__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Imu",
  "Imu",
  "Sensors__Imu",
  "sensors",
  sizeof(Sensors__Imu),
  4,
  sensors__imu__field_descriptors,
  sensors__imu__field_indices_by_name,
  1,  sensors__imu__number_ranges,
  (ProtobufCMessageInit) sensors__imu__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__cam__field_descriptors[4] =
{
  {
    "cols",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__Cam, cols),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rows",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__Cam, rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Sensors__Cam, image_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Cam, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__cam__field_indices_by_name[] = {
  0,   /* field[0] = cols */
  2,   /* field[2] = image_data */
  1,   /* field[1] = rows */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange sensors__cam__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sensors__cam__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Cam",
  "Cam",
  "Sensors__Cam",
  "sensors",
  sizeof(Sensors__Cam),
  4,
  sensors__cam__field_descriptors,
  sensors__cam__field_indices_by_name,
  1,  sensors__cam__number_ranges,
  (ProtobufCMessageInit) sensors__cam__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__lidar__xyz__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Lidar__Xyz, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Lidar__Xyz, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Lidar__Xyz, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__lidar__xyz__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange sensors__lidar__xyz__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sensors__lidar__xyz__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Lidar.xyz",
  "Xyz",
  "Sensors__Lidar__Xyz",
  "sensors",
  sizeof(Sensors__Lidar__Xyz),
  3,
  sensors__lidar__xyz__field_descriptors,
  sensors__lidar__xyz__field_indices_by_name,
  1,  sensors__lidar__xyz__number_ranges,
  (ProtobufCMessageInit) sensors__lidar__xyz__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__lidar__field_descriptors[3] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Lidar, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Sensors__Lidar, n_data),
    offsetof(Sensors__Lidar, data),
    &sensors__lidar__xyz__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Lidar, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__lidar__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = size */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange sensors__lidar__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sensors__lidar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Lidar",
  "Lidar",
  "Sensors__Lidar",
  "sensors",
  sizeof(Sensors__Lidar),
  3,
  sensors__lidar__field_descriptors,
  sensors__lidar__field_indices_by_name,
  2,  sensors__lidar__number_ranges,
  (ProtobufCMessageInit) sensors__lidar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__can__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Can, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Can, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__Can, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__can__field_indices_by_name[] = {
  1,   /* field[1] = data */
  2,   /* field[2] = timestamp */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange sensors__can__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sensors__can__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Can",
  "Can",
  "Sensors__Can",
  "sensors",
  sizeof(Sensors__Can),
  3,
  sensors__can__field_descriptors,
  sensors__can__field_indices_by_name,
  1,  sensors__can__number_ranges,
  (ProtobufCMessageInit) sensors__can__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__log__field_descriptors[6] =
{
  {
    "can_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__Log, can_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_dlc",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__Log, can_dlc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "__pad",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Sensors__Log, __pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "__res0",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Sensors__Log, __res0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "__res1",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Sensors__Log, __res1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Sensors__Log, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__log__field_indices_by_name[] = {
  2,   /* field[2] = __pad */
  3,   /* field[3] = __res0 */
  4,   /* field[4] = __res1 */
  1,   /* field[1] = can_dlc */
  0,   /* field[0] = can_id */
  5,   /* field[5] = data */
};
static const ProtobufCIntRange sensors__log__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sensors__log__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Log",
  "Log",
  "Sensors__Log",
  "sensors",
  sizeof(Sensors__Log),
  6,
  sensors__log__field_descriptors,
  sensors__log__field_indices_by_name,
  1,  sensors__log__number_ranges,
  (ProtobufCMessageInit) sensors__log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__algorithm_img__field_descriptors[5] =
{
  {
    "cols",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__AlgorithmImg, cols),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rows",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__AlgorithmImg, rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_original",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Sensors__AlgorithmImg, image_original),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_result",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Sensors__AlgorithmImg, image_result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "millis_term",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__AlgorithmImg, millis_term),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__algorithm_img__field_indices_by_name[] = {
  0,   /* field[0] = cols */
  2,   /* field[2] = image_original */
  3,   /* field[3] = image_result */
  4,   /* field[4] = millis_term */
  1,   /* field[1] = rows */
};
static const ProtobufCIntRange sensors__algorithm_img__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sensors__algorithm_img__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.algorithm_img",
  "AlgorithmImg",
  "Sensors__AlgorithmImg",
  "sensors",
  sizeof(Sensors__AlgorithmImg),
  5,
  sensors__algorithm_img__field_descriptors,
  sensors__algorithm_img__field_indices_by_name,
  1,  sensors__algorithm_img__number_ranges,
  (ProtobufCMessageInit) sensors__algorithm_img__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sensors__channel_order__enum_values_by_number[6] =
{
  { "GRAYSCALE", "SENSORS__CHANNEL_ORDER__GRAYSCALE", 0 },
  { "BGR", "SENSORS__CHANNEL_ORDER__BGR", 1 },
  { "RGB", "SENSORS__CHANNEL_ORDER__RGB", 2 },
  { "BGRA", "SENSORS__CHANNEL_ORDER__BGRA", 3 },
  { "RGBA", "SENSORS__CHANNEL_ORDER__RGBA", 4 },
  { "OPTICAL_FLOW", "SENSORS__CHANNEL_ORDER__OPTICAL_FLOW", 5 },
};
static const ProtobufCIntRange sensors__channel_order__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex sensors__channel_order__enum_values_by_name[6] =
{
  { "BGR", 1 },
  { "BGRA", 3 },
  { "GRAYSCALE", 0 },
  { "OPTICAL_FLOW", 5 },
  { "RGB", 2 },
  { "RGBA", 4 },
};
const ProtobufCEnumDescriptor sensors__channel_order__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "sensors.ChannelOrder",
  "ChannelOrder",
  "Sensors__ChannelOrder",
  "sensors",
  6,
  sensors__channel_order__enum_values_by_number,
  6,
  sensors__channel_order__enum_values_by_name,
  1,
  sensors__channel_order__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
